service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  create:
    handler: app/server.create
    events:
      - http:
          path: user
          method: post
  update:
    handler: app/server.update
    events:
      - http:
          path: user/{id}
          method: put
  find:
    handler: app/server.find
    events:
      - http:
          path: user
          method: get
  findOne:
    handler: app/server.findOne
    events:
      - http:
          path: user/{id}
          method: get

  deleteOne:
    handler: app/server.deleteOne
    events:
      - http:
          path: user/{id}
          method: delete
